version: "3.7"

services:
  compile:
    build:
      context: .
    volumes:
      - .:/go/src/github.com/terraform-providers/terraform-provider-vault/
      - ../../../../bin:/go/bin
    working_dir: /go/src/github.com/terraform-providers/terraform-provider-vault/
    environment:
      - CGO_ENABLED=0 
      - GOOS=linux 
      - GOARCH=amd64
